services:

  js_container:
    build: ./js_container
#    ports:
#      - "6001-6005:6000"
    volumes:
      - ./js_container/src:/app
    deploy:
      replicas: 5

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - js_container
