services:
  product_service:
    build: ./product_service
#    ports:
#      - "6001-6005:6000"
    volumes:
      - ./product_service/src:/app

  order_service:
    build: ./order_service
    volumes:
      - ./order_service/src:/app

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    restart: on-failure
    depends_on:
      - product_service
      - order_service

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx
      - nginx-exporter

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: ["-nginx.scrape-uri=http://nginx:80/stub_status"]
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus